Implement auth.teams.list api method
slack-go/slack pull request #1037
Opened 2022-02-22 17:38 UTC by DavyJohnes

##### Pull Request Guidelines

These are recommendations for pull requests.
They are strictly guidelines to help manage expectations.

##### PR preparation
Run `make pr-prep` from the root of the repository to run formatting, linting and tests.

##### Should this be an issue instead
- [ ] is it a convenience method? (no new functionality, streamlines some use case)
- [ ] exposes a previously private type, const, method, etc.
- [ ] is it application specific (caching, retry logic, rate limiting, etc)
- [ ] is it performance related.

##### API changes

Since API changes have to be maintained they undergo a more detailed review and are more likely to require changes.

- no tests, if you're adding to the API include at least a single test of the happy case.
- If you can accomplish your goal without changing the API, then do so.
- dependency changes. updates are okay. adding/removing need justification.

###### Examples of API changes that do not meet guidelines:
- in library cache for users. caches are use case specific.
- Convenience methods for Sending Messages, update, post, ephemeral, etc. consider opening an issue instead.

2022-03-18 17:35 UTC, zchee commented
@DavyJohnes Sorry for late, seem to LGTM. will review soon.

2022-04-16 23:48 UTC, kanata2 requested changes
Thanks!

2022-04-16 23:48 UTC, kanata2 commented on users.go
> +
unused?

2022-04-16 23:48 UTC, kanata2 commented on team.go
> +}
`ListAuthTeams` looks better 😄

2022-04-16 23:48 UTC, kanata2 commented on team.go
> +func (api *Client) authTeamsRequest(ctx context.Context, path string, values url.Values) (*AuthTeamsResponse, error) {
This method can be added when `auth.teams` specific processing is needed.

2022-04-16 23:48 UTC, kanata2 commented on team.go
> +func (api *Client) GetAuthTeamsContext(ctx context.Context) ([]TeamInfoShort, error) {
Could you support `include_icon` param?

https://api.slack.com/methods/auth.teams.list

2023-04-17 00:20 UTC, closed without merging