Add `Permalink` to Msg struct
slack-go/slack pull request #1069
Opened 2022-05-27 02:00 UTC by jreinstra

At least in the Slack list-stars method if not others, a permalink is included with each item returned. This permalink is not available via slack-go because it is not a field on the struct used to parse that response, so this change adds that missing field.

##### Pull Request Guidelines

These are recommendations for pull requests.
They are strictly guidelines to help manage expectations.

##### PR preparation
Run `make pr-prep` from the root of the repository to run formatting, linting and tests.

##### Should this be an issue instead
- [ ] is it a convenience method? (no new functionality, streamlines some use case)
- [ ] exposes a previously private type, const, method, etc.
- [ ] is it application specific (caching, retry logic, rate limiting, etc)
- [ ] is it performance related.

##### API changes

Since API changes have to be maintained they undergo a more detailed review and are more likely to require changes.

- no tests, if you're adding to the API include at least a single test of the happy case.
- If you can accomplish your goal without changing the API, then do so.
- dependency changes. updates are okay. adding/removing need justification.

###### Examples of API changes that do not meet guidelines:
- in library cache for users. caches are use case specific.
- Convenience methods for Sending Messages, update, post, ephemeral, etc. consider opening an issue instead.

2022-06-05 23:57 UTC, kanata2 commented on messages.go
> +	Permalink string `json:"permalink,omitempty"
```suggestion
	Permalink string `json:"permalink,omitempty"`
```

2022-06-05 23:58 UTC, kanata2 requested changes
Thanks for your contributions. I commented, please confirm.

2022-06-06 20:06 UTC, jreinstra commented
> Thanks for your contribution! I commented, please confirm.

Oh whoops, accepted fix, thanks!

2022-06-12 21:42 UTC, kanata2 requested changes
I found one minor style-related fix, so please confirm 🙏

2022-06-12 21:42 UTC, kanata2 commented on messages.go
> +
😄 

```suggestion

```

2022-06-14 02:42 UTC, jreinstra commented
> I found one minor style-related fix, so please confirm 🙏

whoops, accepted, thanks!

2022-06-14 13:06 UTC, kanata2 approved these changes
LGTM! Thanks.

2022-06-14 13:58 UTC, merged