Usergroups
slack-go/slack pull request #150
Opened 2017-04-06 06:43 UTC by whiteley

Trying to continue from the previous work to support usergroups

Closes #63 #76

2017-04-17 13:45 UTC, dlsniper requested changes
Hi @whiteley, 

Thanks a lot for your PR.
There are a few changes that should be made before this can be merged.
I really appreciate your PR and the presence of tests.

Thank you.

2017-04-17 13:45 UTC, dlsniper commented on usergroups.go
> +	DeletedBy   string `json:"deleted_by"`
According to the documentation here: https://api.slack.com/types/usergroup ` deleted_by ` can be ` null ` so I guess we need to use ` *string ` as type here.

2017-04-17 13:45 UTC, dlsniper commented on usergroups.go
> +	DateCreate  int    `json:"date_create"`
This should be of type ` JSONTime `

2017-04-17 13:45 UTC, dlsniper commented on usergroups.go
> +	DateUpdate  int    `json:"date_update"`
This should be of type ` JSONTime `

2017-04-17 13:45 UTC, dlsniper commented on usergroups.go
> +	DateDelete  int    `json:"date_delete"`
This should be of type ` JSONTime `

2017-04-17 13:45 UTC, dlsniper commented on usergroups.go
> +	Prefs       struct {
This should be extracted in its own type I think so that it's easier to reference / maintain in the future.

2017-04-18 00:28 UTC, whiteley commented on usergroups.go
> +	DeletedBy   string `json:"deleted_by"`
`deleted_by` can be null or an ID but not an empty string as well, it seemed like that would only be necessary if distinguishing between all three?

2017-04-20 21:29 UTC, dlsniper commented on usergroups.go
> +	Users       []string
I'm not sure if this is needed by the looks of it.

2017-04-20 21:29 UTC, dlsniper commented on usergroups.go
> +	DeletedBy   string `json:"deleted_by"`
As we don't need to encode those I guess it's ok, fair point.

2017-04-20 21:43 UTC, dlsniper requested changes
Hi @whiteley, really sorry for this one last thing, I've missed in my original review. Thank you so much for this.

2017-04-21 09:05 UTC, dlsniper commented
Turns out I can use a cool new Github feature to help on this.
Thanks a lot for the PR @whiteley, awesome job!

2017-04-21 09:05 UTC, dlsniper approved these changes

2017-04-21 09:07 UTC, merged