Enhance GetUserGroups call with params
slack-go/slack pull request #392
Opened 2018-09-01 09:49 UTC by mgouline

- Create `GetUserGroupsParams` struct with field descriptions (from the [docs](https://api.slack.com/methods/usergroups.list#arguments))
- Propagate new parameters to `GetUserGroups` and `GetUserGroupsContext`
- Add list of users to `UserGroup` struct (when `IncludeUsers` is enabled)
- Update unit test to include a list of users

Heavily inspired by #218, which was never merged, but needed the users to be included as well.

2018-09-04 14:56 UTC, james-lawrence requested changes

2018-09-04 14:56 UTC, james-lawrence commented on usergroups.go
> +func NewGetUserGroupsParams() GetUserGroupsParams {
this is kind of pointless, zero value is already false. this entire function can be dropped and replaced with `GetUserGroupsParams{}`

2018-09-04 14:56 UTC, james-lawrence commented on usergroups.go
> +func (api *Client) GetUserGroups(params GetUserGroupsParams) ([]UserGroup, error) {
as this breaks the API, I would recommend switching to an (options ...option) pattern. plenty of examples in the library.

2018-09-05 10:01 UTC, mgouline commented
@james-lawrence thanks for your review, I addressed both comments.

2018-09-05 21:14 UTC, james-lawrence approved these changes

2018-09-05 21:14 UTC, james-lawrence commented
thanks mgouline!

2018-09-05 21:15 UTC, merged