Added auth.revoke endpoint
slack-go/slack pull request #433
Opened 2018-10-17 18:44 UTC by CodeMonk

Added auth.revoke endpoint so that an application can revoke it's oauth tokens.

2018-11-03 19:37 UTC, james-lawrence requested changes
fix the error handling and its GTG.

2018-11-03 19:37 UTC, james-lawrence commented on auth.go
> +	if !response.Ok {
response has an error method for you to use.

2018-11-05 15:50 UTC, CodeMonk commented
Fixed the error handling per review comments.

2018-11-05 18:31 UTC, james-lawrence approved these changes

2018-11-05 18:32 UTC, merged