Add support for unfurling links
slack-go/slack pull request #438
Opened 2018-10-31 05:30 UTC by seanhoughton

Hello, I have added support for the `chat.unfurl` method.

2018-11-03 19:34 UTC, james-lawrence requested changes
error handling needs fixing.

2018-11-03 19:34 UTC, james-lawrence commented on chat.go
> +		return nil
error should be returned in if occurs.

2018-11-07 22:50 UTC, seanhoughton commented
Good catch, I've updated the code to return any error that might happen if the marshal fails.

2018-11-11 12:49 UTC, james-lawrence approved these changes

2018-11-11 12:50 UTC, james-lawrence commented
thanks!

2018-11-11 12:50 UTC, merged