Get Team Custom Fields, Set User Custom Fields
slack-go/slack pull request #474
Opened 2019-02-15 15:16 UTC by MattDavisRV

Added functionality to retrieve defined custom fields from the the Team.  

Added ability to update User custom fields from the information available from the new team request.

2019-02-15 15:26 UTC, MattDavisRV commented
Slack separates Profile and Custom Field update requests.  This was needed to update additional fields that were not apart of the main profile request.  To issue the update request, slack doesn't use a conventional request structure, requiring the need for the map[string]UserCustomProfile. 

Requesting the team custom variables was added to know which IDs to send in the above request.

2019-02-16 20:36 UTC, olivierlemasle approved these changes
:+1:

2019-02-16 20:36 UTC, olivierlemasle commented on users.go
> +// SetUserCustomFieldsContext will set a custom status and emoji for the currently authenticated user with a custom context
Comment is wrong (copy-paste error) ;-)

2019-02-16 21:52 UTC, MattDavisRV commented on users.go
> +// SetUserCustomFieldsContext will set a custom status and emoji for the currently authenticated user with a custom context
Good catch!  Should be fine now

2019-02-24 23:14 UTC, james-lawrence commented
TeamProfile.... not familiar with this part of slacks api. does it represent customization values for the team itself? not the users?

2019-02-25 01:25 UTC, MattDavisRV commented
TeamProfile defines custom fields that belong to the team, but attributed to the user.  They're represented as a ID/Value pair, which can only be retrieved from the added code. 

As an example (in my use case), I've added a custom field called employeeId to the team, then added this attribute to each user to properly identify them during interactive messages (dialogs, etc).

2019-02-27 02:14 UTC, james-lawrence requested changes
one minor comment.

2019-02-27 02:14 UTC, james-lawrence commented on users.go
> +	if !response.Ok {
return response.Err()

2019-03-01 02:41 UTC, james-lawrence commented on users.go
> +	if !response.Ok {
sorry if i wasnt clear. response.Error() does `if !response.Ok {}`

2019-04-22 10:31 UTC, olivierlemasle commented
@MattDavisRV You removed the branch `SetUserCustomFields` from your fork repo. Was it on purpose?

2019-04-28 02:21 UTC, MattDavisRV commented
@olivierlemasle no, it was not on purpose.  Not really sure what happened there.  I've been busy with work.  I'll try to reimplement since it was a small change along with the change requested here.

2019-05-02 01:15 UTC, MattDavisRV commented
I'm waiting for #496 to be completed before I swing back to this PR.  I will complete the requested changes then.

2019-08-31 11:27 UTC, closed without merging