Add block ID parameter to NewSectionBlock method
slack-go/slack pull request #538
Opened 2019-05-30 14:06 UTC by alyosha

## Summary
This change is ultimately a nice to have and may not be worth it. Up to discussion on this one, but my thought process is as follows:

- `SectionBlock` can take any `BlockElement` type under the `Accessory` field, meaning that an action callback can potentially be triggered off of the block 
  - e.g. if providing a `DatePickerBlockElement` as `Accessory` 

- In my projects using `ActionBlocks` blocks so far, I've found it easiest to handle the callback using a switch case on `BlockID`

- Currently, using the `NewSectionBlock` method to generate a new `SectionBlock` results in an empty `BlockID` that is then transformed into a random string at the time of post. 
  - This means that it is not possible to implement a switch like the one described above unless I modify the block value returned from `NewSectionBlock

This is ultimately not crucial, as it is possible to manually update `BlockID` before post, but I find it most convenient to pre-declare all my layout blocks as vars in a single file and then just pick and choose the ones I need.

2019-06-02 10:44 UTC, james-lawrence requested changes
minor suggestion.

2019-06-02 10:44 UTC, james-lawrence commented on block_section.go
> +func NewSectionBlock(blockID string, textObj *TextBlockObject, fields []*TextBlockObject, accessory *Accessory) *SectionBlock {
this method is bettering to the point where you want to do the following:
```
type SectionBlockOption func(*SectionBlock)
func NewSectionBlock(textObj *TextBlockObject, fields []*TextBlockObject, accessory *Accessory, options ...SectionBlockOption) *SectionBlock {
s := &SectionBlock{}
for _, opt := range options {
  opt(s)
}
// ...
```

2019-06-23 05:23 UTC, alyosha commented
@james-lawrence sorry for the delay on this one, updated 👍

2019-06-23 23:28 UTC, james-lawrence approved these changes

2019-06-23 23:28 UTC, james-lawrence commented
thanks!

2019-06-23 23:28 UTC, merged