Add missing omitempty to actionID of some elements
slack-go/slack pull request #717
Opened 2020-05-02 05:15 UTC by nicoJN

I noticed that there are some Block Elements whose actionID doesn't have omitempty property.

- DatePickerBlockElement
- DatePickerBlockElement
- CheckboxGroupsBlockElement
- RadioButtonsBlockElement

Like any other Block Elements, "actionID" is not required. (When we create modal's json by [BlockKit Builder](https://api.slack.com/tools/block-kit-builder?mode=modal), actionID is not attached initially.)

===

In addition, as boyscout, I fix a mistake of a comment of "NewCheckboxGroupsBlockElement".

2020-05-18 15:59 UTC, kanata2 requested changes
As documentation, it seems that `action_id` is required. (ref: https://api.slack.com/reference/block-kit/block-elements#datepicker )
However, the documentation is sometimes outdated, so I want you to verify the actual behavior.

2020-05-18 23:58 UTC, nicoJN commented
Hi, @kanata2 

I verified the behavior of the slack.

## Test item
I send a modal view request with the json below.

```json
{
	"type": "modal",
	"title": {
		"type": "plain_text",
		"text": "My App",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Submit",
		"emoji": true
	},
	"close": {
		"type": "plain_text",
		"text": "Cancel",
		"emoji": true
	},
	"blocks": [
		{
			"type": "input",
			"element": {
				"type": "plain_text_input"
			},
			"label": {
				"type": "plain_text",
				"text": "Singleline Text Input",
				"emoji": true
			}
		}
	]
}
```

Then I inputed text field and pushed a submit button.

## Test result
I got a json like below (Excerpt only some fields).

```
"view": {
        ...
        "blocks": [
            {
                "type": "input",
                "block_id": "Kzpss",
                "label": {
                    "type": "plain_text",
                    "text": "Singleline Text Input",
                    "emoji": true
                },
                "optional": false,
                "element": {
                    "type": "plain_text_input",
                    "action_id": "wCK"
                }
            }
        ],
        ...
        "state": {
            "values": {
                "Kzpss": {
                    "wCK": {
                        "type": "plain_text_input",
                        "value": "TEST"
                    }
                }
            }
        },
        ...
    },
```

### Conclusion
If we don't attach action_id and block_id to some elements, slack automatically add some IDs.

## Further discussion
I think the biggest problem is that It's difficult to analyze the problem for slack-go/slack users with the current specifications.

If we don't attach action_id, slack-go/slack automatically add action_id field with empty string.

```
action_id: ""
```

And then, If we send a modal with `action_id: ""` (func Openview), it returns an error.

```
err invalid_arguments
```

The root cause of the error is that the action_id field must be contain more than 0 characters.

![image](https://user-images.githubusercontent.com/22317839/82269173-cdd58000-99ab-11ea-8536-7363190ebfc3.png)

Unfortunately, return values of func Openview don't contain this information. So users can see the error reason by only using Block Kit Builder. 
It makes it difficult to analyze the problem.

If we add `omitempty` to action_id field, users can successfully send a modal view and get input values like mentioned above, and can notice that they should add action_id field expressly to make  easy to parse the values.

I think it's a more user friendly behavior.

2020-05-31 08:58 UTC, nicoJN commented
Hi, @kanata2 !
Is there anything else which I should validate? Feel free to offer me additional test👍

2020-05-31 21:02 UTC, ollieparsley approved these changes
Thank you @nicoJN

2020-05-31 21:03 UTC, merged