Add integration logs api
slack-go/slack pull request #920
Opened 2021-04-05 15:01 UTC by naormatania

Add support for https://api.slack.com/methods/team.integrationLogs 
Add unittest to check it works as expected
Also ran `make pr-prep` to check it's ready for review

2021-04-18 16:11 UTC, kanata2 reviewed
Looks good except for the parts I pointed out!

2021-04-18 16:11 UTC, kanata2 commented on team.go
> +type Log struct {
Please add `Channel` field.

2021-04-19 05:47 UTC, naormatania commented on team.go
> +type Log struct {
Thanks for the feedback
done

2021-04-20 23:00 UTC, kanata2 commented
@naormatania 
When I tried it, I came across strange behavior.
Slack documentation says that the `service_id` field is string, but actual response's one is not string but int and then could not unmarshal by slack-go/slack. I'll confirm Slack support.

2021-05-11 08:24 UTC, naorsec commented
@kanata2 has slack support answered about this issue ?

2021-05-11 08:33 UTC, kanata2 commented
Sorry for delay.
According to support, this is documentation's mistake.

2021-05-17 17:57 UTC, naormatania commented
@kanata2 it seems like slack updated their documentation that `service_id` can be both int or string.
I changed PR to handle both cases. let me know what you think. thanks !

2021-05-19 02:01 UTC, kanata2 commented
@naormatania 
I confirmed support again.
According to support's response, the type of `service_id` is only integer, so we do not seem to need to consider the string type. :sob:

2021-05-21 04:57 UTC, naormatania commented
Thanks for the help @kanata2 ! I changed it to `int` now

2021-05-30 21:45 UTC, kanata2 commented
thanks!
I found a new undocumented behavior...
It seems that the `user_id` can be 0 (= a number).

```json
        {
            "user_id": 0,
            "user_name": "slack",
            "date": "1595673313",
            "change_type": "disabled",
            "reason": "channel_archive",
            "service_id": 123456789,
            "service_type": "Incoming WebHooks",
            "scope": "incoming-webhook"
        }
```

2021-06-01 12:56 UTC, dorsec requested changes

2021-06-01 12:56 UTC, dorsec commented on team.go
> +	Date        string `json:"date"`
```go
DateTime   JSONTime `json:"date,string"`
```

2021-06-01 12:56 UTC, dorsec commented on team.go
> +	UserID      string `json:"user_id"`
stringOrInt

2023-04-17 00:20 UTC, closed without merging